// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: rpcpb/services.proto

package rpcpb

import (
	clientpb "github.com/longzekun/specter/protobuf/clientpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rpcpb_services_proto protoreflect.FileDescriptor

const file_rpcpb_services_proto_rawDesc = "" +
	"\n" +
	"\x14rpcpb/services.proto\x12\x05rpcpb\x1a\x15clientpb/client.proto2S\n" +
	"\n" +
	"SpecterRPC\x12E\n" +
	"\x11StartMTLSListenet\x12\x19.clientpb.MTLSListenerReq\x1a\x15.clientpb.ListenerJobB-Z+github.com/longzekun/specter/protobuf/rpcpbb\x06proto3"

var file_rpcpb_services_proto_goTypes = []any{
	(*clientpb.MTLSListenerReq)(nil), // 0: clientpb.MTLSListenerReq
	(*clientpb.ListenerJob)(nil),     // 1: clientpb.ListenerJob
}
var file_rpcpb_services_proto_depIdxs = []int32{
	0, // 0: rpcpb.SpecterRPC.StartMTLSListenet:input_type -> clientpb.MTLSListenerReq
	1, // 1: rpcpb.SpecterRPC.StartMTLSListenet:output_type -> clientpb.ListenerJob
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpcpb_services_proto_init() }
func file_rpcpb_services_proto_init() {
	if File_rpcpb_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpcpb_services_proto_rawDesc), len(file_rpcpb_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpcpb_services_proto_goTypes,
		DependencyIndexes: file_rpcpb_services_proto_depIdxs,
	}.Build()
	File_rpcpb_services_proto = out.File
	file_rpcpb_services_proto_goTypes = nil
	file_rpcpb_services_proto_depIdxs = nil
}
