// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: rpcpb/services.proto

package rpcpb

import (
	context "context"
	clientpb "github.com/longzekun/specter/protobuf/clientpb"
	commonpb "github.com/longzekun/specter/protobuf/commonpb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpecterRPC_StartMTLSListener_FullMethodName = "/rpcpb.SpecterRPC/StartMTLSListener"
	SpecterRPC_Events_FullMethodName            = "/rpcpb.SpecterRPC/Events"
)

// SpecterRPCClient is the client API for SpecterRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpecterRPCClient interface {
	// **********listener************
	StartMTLSListener(ctx context.Context, in *clientpb.MTLSListenerReq, opts ...grpc.CallOption) (*clientpb.ListenerJob, error)
	Events(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[clientpb.Event], error)
}

type specterRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewSpecterRPCClient(cc grpc.ClientConnInterface) SpecterRPCClient {
	return &specterRPCClient{cc}
}

func (c *specterRPCClient) StartMTLSListener(ctx context.Context, in *clientpb.MTLSListenerReq, opts ...grpc.CallOption) (*clientpb.ListenerJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(clientpb.ListenerJob)
	err := c.cc.Invoke(ctx, SpecterRPC_StartMTLSListener_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *specterRPCClient) Events(ctx context.Context, in *commonpb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[clientpb.Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpecterRPC_ServiceDesc.Streams[0], SpecterRPC_Events_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[commonpb.Empty, clientpb.Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpecterRPC_EventsClient = grpc.ServerStreamingClient[clientpb.Event]

// SpecterRPCServer is the server API for SpecterRPC service.
// All implementations must embed UnimplementedSpecterRPCServer
// for forward compatibility.
type SpecterRPCServer interface {
	// **********listener************
	StartMTLSListener(context.Context, *clientpb.MTLSListenerReq) (*clientpb.ListenerJob, error)
	Events(*commonpb.Empty, grpc.ServerStreamingServer[clientpb.Event]) error
	mustEmbedUnimplementedSpecterRPCServer()
}

// UnimplementedSpecterRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpecterRPCServer struct{}

func (UnimplementedSpecterRPCServer) StartMTLSListener(context.Context, *clientpb.MTLSListenerReq) (*clientpb.ListenerJob, error) {
	return nil, status.Error(codes.Unimplemented, "method StartMTLSListener not implemented")
}
func (UnimplementedSpecterRPCServer) Events(*commonpb.Empty, grpc.ServerStreamingServer[clientpb.Event]) error {
	return status.Error(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedSpecterRPCServer) mustEmbedUnimplementedSpecterRPCServer() {}
func (UnimplementedSpecterRPCServer) testEmbeddedByValue()                    {}

// UnsafeSpecterRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpecterRPCServer will
// result in compilation errors.
type UnsafeSpecterRPCServer interface {
	mustEmbedUnimplementedSpecterRPCServer()
}

func RegisterSpecterRPCServer(s grpc.ServiceRegistrar, srv SpecterRPCServer) {
	// If the following call panics, it indicates UnimplementedSpecterRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpecterRPC_ServiceDesc, srv)
}

func _SpecterRPC_StartMTLSListener_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(clientpb.MTLSListenerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpecterRPCServer).StartMTLSListener(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpecterRPC_StartMTLSListener_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpecterRPCServer).StartMTLSListener(ctx, req.(*clientpb.MTLSListenerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpecterRPC_Events_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(commonpb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SpecterRPCServer).Events(m, &grpc.GenericServerStream[commonpb.Empty, clientpb.Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpecterRPC_EventsServer = grpc.ServerStreamingServer[clientpb.Event]

// SpecterRPC_ServiceDesc is the grpc.ServiceDesc for SpecterRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpecterRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpcpb.SpecterRPC",
	HandlerType: (*SpecterRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartMTLSListener",
			Handler:    _SpecterRPC_StartMTLSListener_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Events",
			Handler:       _SpecterRPC_Events_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpcpb/services.proto",
}
